README.md, examples/load_elf.rs, examples/to_json.rs, src/disassembler.rs, src/ebpf.rs, src/jit.rs, src/lib.rs, src/verifier.rs, tests/misc.rs
As promised here are a few Rust-y details to your code.
I ran [cargo-clippy](https://github.com/Manishearth/rust-clippy) against the code and fixed nearly all of the warnings.
A list of some of the changes:
1. Slice instead of Vec. [`ptr_arg`](https://github.com/Manishearth/rust-clippy/wiki#ptr_arg)
2. Don't re-borrow slices. [`needless_borrow`](https://github.com/Manishearth/rust-clippy/wiki#needless_borrow)
3. Useless use of vec. [`useless_vec`](https://github.com/Manishearth/rust-clippy/wiki#useless_vec)
4. …and a few more. [Full log of clippy against the master branch](https://gist.github.com/badboy/dee55394f010597413cd9ae806da0953)
I even changed `&mut Vec` to `&mut []` (i.e. a mutable vector to a mutable slice, as afaik it should not be possibleto resize the passed array, but only …
=> Use slices & references

src/ebpf.rs
=> Fix spelling error in comment.

Cargo.toml, src/asm_parser.rs, src/lib.rs, tests/asm_parser.rs
Uses the combine crate to parse ubpf-style assembly to Instruction
structs. A future assembler module will consume these, check that
the instruction and operands are valid, and output ebpf::Insn.
=> add assembly parser

src/disassembler.rs, tests/disassembler.rs
Debugging my own BPF programs I noticed a wrong output in the disassembler.
This fixes it, see the first two commits.
I added tests for the disassembler output by roundtripping through the assembler (so it's easier to write). I more or less took all assembler tests, only removed the error-case ones and some which used shortened instructions (`add` instead of `add64`). This testing is not perfect, but should catch a mismatch here.
=> Correct disasm

src/jit.rs
This was recently removed from Rust. With this patch there is no "unknown lint" warning on Rust 1.17 anymore.
Older versions should still work, though maybe with a warning about `single_match`
I'm not sure what `single_match` would have complained about before.
=> Remove no-longer-existing lint

.travis.yml, Cargo.toml, src/helpers.rs, src/lib.rs
This uses the `time` crate, which is marked as deprecated, but it is still maintained. They suggest using `chrono` instead, but that's far larger and what's needed here is so small that it isn't reasonable.
=> Use time crate for nanosecond times

src/disassembler.rs
These checks are already performed by to_insn_vec().
=> Remove redundant checks from disassemble().

Cargo.toml
This is what various tools expect, like `cargo outdated`.
=> Use [package] in Cargo.toml

Cargo.toml, src/ebpf.rs, src/jit.rs, src/lib.rs
Interested in using rBPF for a project I'm working on so fixed a couple of clippy errors/warnings.  If this project is still active and these changes are approved would like to fix more
- pulled byteorder dependency back in to avoid unsafe code and to fix clippy casting errors
- removed copy of operand that was not consumed
=> fix clippy error: cast to more strict alignment, warning: not consumed copy

Cargo.toml, README.md
Bump version number to release a new crate version.
We're not-so-stable yet, especially with all the changes we had other the last days, so it seems early to change the major version. On the other hand, we got many changes since the previous version of the crate: assembler, disassembler, Rust API to build programs; custom verifiers; error handling; many fixes, etc. So we'll bump the second digit and tag version 0.1.0.
=> Cargo.toml: upgrade to version 0.1.0

src/disassembler.rs, src/jit.rs
As explained in the commit message of 038ddf7:
> https://doc.rust-lang.org/std/fmt/trait.LowerHex.html says "For primitive signed integers (i8 to i128, and isize), negative values are formatted as the two’s complement representation."
> 
> As such, we can't rely on Rust's "+" formatting flag when writing instruction offsets.
=> fix how the disassembler handles offsets

examples/load_elf.rs, examples/to_json.rs, src/asm_parser.rs, src/assembler.rs, src/disassembler.rs, src/helpers.rs, src/jit.rs, src/lib.rs, src/verifier.rs, tests/misc.rs
We addressed reports from Clippy in previous commits, see for example commit 153995b3a367 ("Let cargo-clippy lint the code"). But it looks like the latest version of the linter applies more checks, and the GitHub workflow in the CI is raising warnings. Let's address all these reports.
=> src: Address newer reports from cargo-clippy

src/verifier.rs, tests/ubpf_verifier.rs
Programs don't always have to have their list of instructions ending with an `exit` instruction, they can jump backwards to a branch ending with `exit`.
We don't have the checks to validate that all branches end with `exit` in the verifier, but we can allow the last instruction to be a backward jump, at least.
Fixes: #62
=> src/verifier.rs: Allow ending with backward jumps

.github/workflows/test.yaml
This test was disabled because of #62, but the issue has been solved. We can now run this test in the CI.
=> ci: Enable exit-not-last test in conformance tests

src/lib.rs
There are a few unnecessary casts that were introduced with support for 32-bit jump instructions in the interpreter. Let's remove them.
=> src/lib.rs: Fix clippy reports introduced with 32-bit jumps support

.github/workflows/test.yaml
Capture code coverage for the tests run during CI/CD.
Use the https://github.com/taiki-e/cargo-llvm-cov tools chain to convert coverage into lcov-based report.
Upload report to a free (for OSS) site that permits tracking code coverage data over time.
Signed-off-by: Alan Jowett <alanjo@microsoft.com>
=> Capture code coverage and upload

README.md
It seems that these type should be `Result`
=> README: fix example type err

README.md, examples/rbpf_plugin.rs, src/lib.rs
- README.md: Use Option to pass programs when building new VMs in examples
- README.md: Fix example by using an existing object file
- README.md: Adjust Windows execution for examples with JIT compiler 
- src/lib.rs: Make "cargo test" run on examples from README.md
- README.md: Add coverage status badge
- README.md: State DCO requirement explicitly
- examples/rbpf_plugin.rs: Fix minor reports from clippy
=> README.md adjustments (and a few more minor things)

src/lib.rs
Some spaces were introduced by accident at the end of a few lines. This is a simple clean-up to remove them.
=> src/lib.rs: Remove spurious spaces at end of lines

Cargo.toml, src/helpers.rs
The time crate version used in rbpf [has a security issue](https://rustsec.org/advisories/RUSTSEC-2020-0071) (though the use of it in this library is secure). Update the time crate version to make the audits of the crates which depend on rbpf succeed.
=> deps: update time crate version.

src/jit.rs
To avoid cargo printing debug assertions about misaligned pointer dereferences when JIT-compiling programs for the tests, fix the way we write the bytes to explicitly tell rustc we may have misaligned accesses. No functional change.
Related: #77
=> jit.rs: When emitting bytes, mark writing as unaligned

Cargo.toml, src/helpers.rs, src/lib.rs, tests/misc.rs
Fixes https://github.com/qmonnet/rbpf/issues/77
I ran this to find all the issues fixed here:
```
RUSTDOCFLAGS=-Zsanitizer=address ASAN_OPTIONS=detect_leaks=0 RUSTFLAGS=-Zsanitizer=address cargo +nightly test --target=x86_64-unknown-linux-gnu
```
ASan is still grumpy because `JitMemory` leaks the `contents` allocation. This is probably fine in practice I think because there won't be more than one JIT in a process? But if you want you could also add a `Drop` impl.
It would probably be good to use the above invocation when doing stuff in CI, but I'm awful with GitHub actions so I'll leave that to you if you want to do it.
=> Fix alignment issues (and a test-only buffer overflow)

.appveyor.yml, .github/workflows/test.yaml, Cargo.toml, README.md, src/lib.rs
- ci: Remove empty workflow file
- rbpf: Rename "master" branch into "main" everywhere in the repo
- Cargo.toml,README.md: Bump version to 0.2.0
=> Rename `master` into `main`, bump crate version

Cargo.toml, src/asm_parser.rs
Not sure if you are willing to accept this PR, but nonetheless since I already did it. Currently, this crate uses `combine` crate version 2.5, which is a very old version. The latest version is `4.6`. 
I understand that using an older version by itself is not an issue. I decided to go down this rabbit hole because I noticed the following security notification from dependabot on one of the project I am working on.
```
Dependabot cannot update ascii to a non-vulnerable version
The latest possible version of ascii that can be installed is 0.7.1.
The earliest fixed version is 0.9.3.
```
The older version of `combine` uses the `ascii` crate. However, the latest version of `combine` version 4.6 no longer has this dependency.
Since the major version changed from 2 -> 4, there are breaking …
=> bump combine version

src/jit.rs, tests/ubpf_jit_x86_64.rs
When dividing by the content of a register, we have a specific case to handle divisions by zero. When the denominator is not 0, we skip the related instructions by emitted a near jump with the relevant offset.
However, this offset was incorrect. We accounted for two instructions: a 2-byte long XOR of the destination register with itself to set it to 0, and a 5-byte long jump. The former may in fact emit 3 bytes under certain condition, depending on the destination in use. For example, when dividing from r7, we emit 3 bytes, and the fixed offset of 7 bytes we used is incorrect, and triggers a segfault.
To fix this, let's add a check to determine the offset value we should use. We also add related tests to make sure we don't regress on this in the future.
Closes: …
=> src/jit.rs: Fix offset when skipping insns for handling divisions by 0

src/interpreter.rs, tests/ubpf_vm.rs
=> Fix overflow issue in memory address boundary check

src/interpreter.rs, tests/ubpf_vm.rs
The current version of [the BPF Instruction Set Specification][ietf] specifies that "Shift operations use a mask of 0x3F (63) for 64-bit operations and 0x1F (31) for 32-bit operations".
The current implementation is not compliant, and Rust complains if we overflow the number of bits we have when trying to shift. Let's fix it, and let's complete the test suite regarding left and right shift operations.
Note: The JITs are not updated at this stage. The standard does no. mention any difference between JIT and interpreter, but the kernel clearly considers the masking for the interpreter only. JIT-compilers are supposed to handle the overflow case in an implementation-defined (architecture-dependant) fashion. Kernel also use masking for shifts with registers only (not immediates) and handles …
=> src/interpreter.rs: Fix left/right shifts implementation (mask offset)

.appveyor.yml
Don't pin to a specific version in Appveyor. This is less deterministic for the tests, but because we don't run them often anyway we want to use up-to-date versions when we do. And this is consistent with the Linux workflows.
=> .appveyor.yml: Use 'stable' channel for Rust version

src/helpers.rs, src/jit.rs
I observed the following warning while running the tests, let's address
them:
warning: the item `time` is imported redundantly
--> src/helpers.rs:22:5
|
22 | use time;
|     ^^^^
|
::: src/lib.rs:32:1
|
32 | extern crate time;
| ------------------ the item `time` is already imported here
|
= note: `#[warn(unused_imports)]` on by default
warning: the item `std` is imported redundantly
--> src/jit.rs:8:5
|
8 | use std;
|     ^^^ the item `std` is already imported by prelude
=> src: Remove unused imports raised by linter

src/interpreter.rs
Fix #101 
We mask the mask offset for arithmetic shifts operaitons. The current version of the BPF Instruction Set Specification specifies that "Shift operations use a mask of 0x3F (63) for 64-bit operations and 0x1F (31) for 32-bit operations" [0].
[0]: https://www.ietf.org/archive/id/draft-thaler-bpf-isa-02.html#section-3.1-2.2.16.1.1
=> src/interpreter.rs: Fix arithmetic left/right shift implementation (mask offset)

src/interpreter.rs, tests/ubpf_vm.rs
- tests/ubpf_vm.rs: Add tests for arsh offset masking
- src/interpreter: Remove/explain masks for 32-bit shift operations
Cc: @pcy190
=> Follow-up for masks on shift operations

.github/workflows/test.yaml, Cargo.toml, README.md, examples/rbpf_plugin.rs, examples/uptime.rs, src/asm_parser.rs, src/assembler.rs, src/cranelift.rs, src/disassembler.rs, src/ebpf.rs, src/helpers.rs, src/insn_builder.rs, src/interpreter.rs, src/lib.rs, src/no_std_error.rs, src/verifier.rs, tests/misc.rs, tests/ubpf_jit_x86_64.rs
Added support for rbpf to run on `no_std` environments. 
Using rbpf on targets without `std` support increases compatibility of the crate. 
I've been using a modified version of rbpf to run eBPF programs on microcontrollers (see [here(https://github.com/SzymonKubica/mibpf))
Currently the code builds successfuly with both configuration options enabled, i.e. all build configurations succeed:
```
cargo build
cargo build --features cranelift
cargo build --no-default-features
cargo build --features cranelift --no-default-features
```
All tests (except for the ones using the `print` - only available in std) pass in both configuration options.
The structure of `std` / `no_std` feature-gating is inspired by `serde`, inside of `lib.rs` a public module: `lib` is defined and it 
contains reexports …
=> Add no_std compatibility

Cargo.toml, README.md
Commits:
- **Cargo.toml: Update author email**
- **Cargo.toml,README.md: Bump version to 0.3.0**
We got a bunch of new features since version 0.2.0, in particular:
- A new JIT-compiling infrastructure via Cranelift (opt-in feature)
- The ability to compile and use most of rbpf's features without the standard library
- An API update to allow eBPF helpers to use designated memory area in our simple verifier, so that users can hook their map implementation
- Several bug fixes
Let's update the crate so that users can benefit from these.
=> Version bump (0.3.0)

examples/allowed-memory/README.md
I realized that I forgot to add the README with the compilation instructions.
=> fix(doc): Add compilation instructions for aya ebpf example

src/interpreter.rs
Rust 1.83 introduces some [additional out-of-bound checks][0], making it illegal to attempt to load at an out-of-bound access when trying to load/store values from/to register in rbpf's interpreter, and causing the program to panick even before we reach the safety checks from `check_mem()`.
I understand we need to use `wrapping_offset()` rather than `offset()` in that case, which causes the operation itself (but not the resulting poitner) to be safe, and the checked to be deferred. See also the [related GitHub issue][1].
[0]: https://github.com/rust-lang/rust/pull/130251
[1]: https://github.com/qmonnet/rbpf/issues/115
Fixes: #115
=> src/interpreter.rs: Use wrapping_offset() for load/store operations

src/helpers.rs, src/jit.rs
I am attempting to reduce the dependence on libc in my indirect
dependencies. While looking at this crate I noticed some low-hanging
fruit that can be very easily replaced with libc.
- The rand() function can be re-implemented as a simple Wyrand seeded by
the thread ID and the current time.
- libc::memcpy is used at a point where it can be replaced with
ptr::copy_nonoverlapping.
- libc is used for memory allocation at a point where std::alloc can be
used instead. So I use this.
I'm not too familiar with this codebase, so if any of these replacements
are incorrect, please let me know.
The only leftover libc call is mprotect().
=> Reduce usage of libc

.github/workflows/test.yaml, Cargo.toml, examples/allowed_memory.rs, examples/load_elf.rs, examples/rbpf_plugin.rs, src/cranelift.rs, src/ebpf.rs, src/helpers.rs, src/insn_builder.rs, src/interpreter.rs, src/jit.rs, src/lib.rs, tests/assembler.rs, tests/cranelift.rs, tests/misc.rs, tests/ubpf_jit_x86_64.rs, tests/ubpf_vm.rs
- src: Fix deprecated calls to 'feature = "cargo-clippy"'
- src: Fix Clippy reports
- ci: Add features to clippy pass
- src: Remove presumably unused Clippy directives
=> Clippy update

src/interpreter.rs, tests/ubpf_vm.rs
fix the signed/unsigned comparisons in several jump instructions in the `execute_program` function
Key changes include:
* Added a new macro `unsigned_u64!` to convert immediate values to unsigned 64-bit integers (i can be simply written as inst.imm as u32 as u64, the macro is just for better readability, **i can change it back to the simpler version if you wish**)
* Updated the implementation of several jump instructions (`JEQ_IMM`, `JGT_IMM`, `JGE_IMM`, `JLT_IMM`, `JLE_IMM`, `JNE_IMM`) to use the new `unsigned_u64!` macro, ensuring correct handling of unsigned comparisons.
- https://docs.kernel.org/bpf/standardization/instruction-set.html#jump-instructions
=> fix: clarify signed & unsigned for jump insts
